<a href="https://colab.research.google.com/github/PriyanshuChaudhary00/English_to_hindi_using_encoder_decoder/blob/main/encoder_decoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# #!/bin/bash
# !kaggle datasets download preetviradiya/english-hindi-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/preetviradiya/english-hindi-dataset
License(s): GNU Free Documentation License 1.3
english-hindi-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
# !unzip english-hindi-dataset.zip

Archive:  english-hindi-dataset.zip
replace Dataset_English_Hindi.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Dataset_English_Hindi.csv")

In [ ]:
df.head()

  English    Hindi
0   Help!    बचाओ!
1   Jump.    उछलो.
2   Jump.    कूदो.
3   Jump.   छलांग.
4  Hello!  नमस्ते।

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130476 entries, 0 to 130475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   English  130474 non-null  object
 1   Hindi    130164 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [ ]:
df["English"] = df["English"].str.lower().str.split()
df["Hindi"] = df["Hindi"].str.split()

In [ ]:
df.head()

    English      Hindi
0   [help!]    [बचाओ!]
1   [jump.]    [उछलो.]
2   [jump.]    [कूदो.]
3   [jump.]   [छलांग.]
4  [hello!]  [नमस्ते।]

In [ ]:
df["Hindi"] = df["Hindi"].apply(
    lambda x: ["<start>"] + x + ["<end>"] if isinstance(x, list) else ["<start>", "<end>"]
    )

In [ ]:
df.head()

    English                      Hindi
0   [help!]    [<start>, बचाओ!, <end>]
1   [jump.]    [<start>, उछलो., <end>]
2   [jump.]    [<start>, कूदो., <end>]
3   [jump.]   [<start>, छलांग., <end>]
4  [hello!]  [<start>, नमस्ते।, <end>]

In [43]:
vocab_english = []
for i , sentance in enumerate(df["English"]) :
  vocab_english.extend(sentance)
  print(sentance)
  if i == 5 :break
print(vocab_english)

['help!']
['jump.']
['jump.']
['jump.']
['hello!']
['hello!']
['help!', 'jump.', 'jump.', 'jump.', 'hello!', 'hello!']

In [ ]:
vocab_hindi = []